import { AppShell } from '@/components/app-shell';
import { getAnalyses } from '@/lib/intelligence-data';
import { createClient } from '@supabase/supabase-js';

async function trendData(){
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
  if(!url||!key)return [];
  const c=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data}=await c.from('trend_snapshots').select('*,problems(title)').order('period_end',{ascending:false}).limit(100);
  return data||[];
}

export default async function TrendsPage(){const rows=await getAnalyses(200),snapshots=await trendData();const tech=new Map<string,number>(),segments=new Map<string,number>();for(const a of rows){for(const t of a.technologies||[])tech.set(t,(tech.get(t)||0)+1);for(const s of a.customer_segments||[])segments.set(s,(segments.get(s)||0)+1)}const topTech=[...tech.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10),topSegments=[...segments.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10),avg=rows.length?Math.round(rows.reduce((s,a)=>s+Number(a.demand_score||0),0)/rows.length):0;return <AppShell active="Trends"><div className="content"><div className="eyebrow">Market movement</div><h1>Where demand is concentrating.</h1><p className="lead">Trend snapshots compare recurring problem signals over time. Growth becomes meaningful as repeated manual discovery runs accumulate history.</p><div className="grid"><div className="card"><div className="muted">Current average demand</div><div className="metric">{avg}</div></div><div className="card"><div className="muted">Tracked problem trends</div><div className="metric">{new Set(snapshots.map((x:any)=>x.problem_id)).size}</div></div><div className="card"><div className="muted">Technology signals</div><div className="metric">{tech.size}</div></div><div className="card"><div className="muted">Analyzed signals</div><div className="metric">{rows.length}</div></div></div><div className="section two-col"><div className="card"><h2>Emerging problem movement</h2>{snapshots.length?snapshots.slice(0,15).map((x:any)=><div className="trend" key={x.id}><div><div className="title-cell">{x.problems?.title||'Problem'}</div><div className="small">{x.mentions} mentions · demand {Math.round(Number(x.demand_score||0))}</div></div><strong>{x.growth_rate==null?'—':`${Number(x.growth_rate).toFixed(0)}%`}</strong></div>):<div className="empty">No trend history yet. Run a discovery pass and build history over time.</div>}</div><div className="card"><h2>Technology concentration</h2>{topTech.length?topTech.map(([n,v])=><div className="trend" key={n}><span>{n}</span><strong>{v}</strong></div>):<div className="empty">Not enough data yet.</div>}<h2 style={{marginTop:24}}>Customer demand</h2>{topSegments.slice(0,6).map(([n,v])=><div className="trend" key={n}><span>{n}</span><strong>{v}</strong></div>)}</div></div></div></AppShell>}
