'use client';
import { useEffect, useState } from 'react';

type Run={id:string;status:string;topic:string|null;signals_collected:number;signals_analyzed:number;problems_found:number;opportunities_found:number;started_at:string;completed_at?:string|null;error?:string|null};
type Topic={id:string;topic:string;priority:number;last_researched_at?:string|null;times_researched:number};
export function AutonomousDashboard({initialRuns,initialTopics}:{initialRuns:Run[];initialTopics:Topic[]}){
 const [runs,setRuns]=useState(initialRuns),[topics,setTopics]=useState(initialTopics),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function refresh(){const r=await fetch('/api/autonomous/status',{cache:'no-store'});if(r.ok){const j=await r.json();setRuns(j.runs||[]);setTopics(j.topics||[]);}}
 useEffect(()=>{const id=setInterval(refresh,30000);return()=>clearInterval(id)},[]);
 async function runNow(){setBusy(true);setMsg('Agent is discovering a new market, collecting evidence and analyzing demand…');try{const r=await fetch('/api/autonomous/run-now',{method:'POST'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Discovery failed');setMsg(`Completed ${j.topic}: ${j.analysis?.opportunities||0} opportunities identified.`);await refresh();}catch(e:any){setMsg(e?.message||'Autonomous discovery failed')}finally{setBusy(false)}}
 const analyzed=runs.reduce((n,r)=>n+Number(r.signals_analyzed||0),0),problems=runs.reduce((n,r)=>n+Number(r.problems_found||0),0),opps=runs.reduce((n,r)=>n+Number(r.opportunities_found||0),0),latest=runs[0];
 return <div className="section">
  <div className="card"><div className="section-head"><div><div className="eyebrow">Autonomous product discovery</div><h2 style={{margin:0}}>Find what people need — without giving Soln-Agent a topic.</h2></div><button onClick={runNow} disabled={busy}>{busy?'Discovering…':'Run discovery now'}</button></div><p className="lead" style={{fontSize:15}}>Soln-Agent continuously explores public conversations, detects recurring customer problems, tracks demand and turns strong patterns into product opportunities. Topic research is an optional deep-dive, not the main workflow.</p>{msg&&<div className="note">{msg}</div>}<div className="stat-grid" style={{marginTop:16}}><div className="stat"><div className="small">Agent</div><strong>{latest?.status==='running'?'Running':'Ready'}</strong></div><div className="stat"><div className="small">Signals analyzed</div><strong>{analyzed}</strong></div><div className="stat"><div className="small">Problems</div><strong>{problems}</strong></div><div className="stat"><div className="small">Opportunities</div><strong>{opps}</strong></div></div></div>
  <div className="two-col" style={{marginTop:16}}><div className="card"><div className="section-head"><h3>Agent activity</h3><span className="small">Latest discovery cycles</span></div>{runs.length?runs.slice(0,6).map(r=><div className="trend" key={r.id}><div><div className="title-cell">{r.topic||'Discovery cycle'}</div><div className="small">{r.status} · {r.signals_analyzed} analyzed · {r.problems_found} problems · {r.opportunities_found} opportunities</div></div><div className="small">{new Date(r.started_at).toLocaleString()}</div></div>):<div className="empty">No autonomous cycles yet. Run the agent or connect the scheduled n8n trigger.</div>}</div><div className="card"><div className="section-head"><h3>Discovery universe</h3><span className="small">Agent rotates through these areas</span></div>{topics.map(t=><div className="trend" key={t.id}><div><div className="title-cell">{t.topic}</div><div className="small">Priority {t.priority} · researched {t.times_researched}×</div></div><div className="small">{t.last_researched_at?new Date(t.last_researched_at).toLocaleDateString():'Queued'}</div></div>)}</div></div>
 </div>;
}
