import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { isApiAuthorized } from '@/lib/api-auth';

export const maxDuration = 50;
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});
const strip=(s:string)=>String(s||'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const unwrap=(value:string)=>{try{const raw=value.startsWith('//')?`https:${value}`:value;const u=new URL(raw);const x=u.searchParams.get('uddg');return x?decodeURIComponent(x):raw}catch{return value}};
async function search(q:string){const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0 Soln-Agent'},cache:'no-store'});if(!r.ok)return[];const h=await r.text(),out:any[]=[];const anchors=[...h.matchAll(/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)];const snippets=[...h.matchAll(/class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)(?:<\/a>|<\/div>|<\/span>)/gi)].map(x=>strip(x[1]));for(let i=0;i<anchors.length&&out.length<15;i++){const m=anchors[i],url=unwrap(strip(m[1]));if(!url||out.some(x=>x.url===url))continue;out.push({url,title:strip(m[2]),snippet:snippets[i]||''});}return out;}
async function enrich(items:any[],context:string){const key=process.env.GEMINI_API_KEY;if(!key)return items.map(x=>({...x,pricing:null,features:[],complaints:[],strengths:[],weaknesses:[],confidence:35}));const model=process.env.GEMINI_MODEL||'gemini-3.1-flash-lite';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:'Analyze competitor evidence only. Never invent facts. Return JSON array with name,url,description,pricing,features,complaints,strengths,weaknesses,confidence. Confidence must reflect the evidence in the supplied search results, not general model knowledge.'}]},contents:[{role:'user',parts:[{text:JSON.stringify({opportunity:context,results:items})}]}],generationConfig:{temperature:0,responseMimeType:'application/json'}})});if(!r.ok)return items;const j=await r.json(),t=j.candidates?.[0]?.content?.parts?.[0]?.text;try{return JSON.parse(t||'[]')}catch{return items}}

export async function POST(req:NextRequest){if(!(await isApiAuthorized(req)))return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json().catch(()=>({})),oid=String(b?.opportunity_id||'');if(!oid)return NextResponse.json({error:'opportunity_id is required'},{status:400});const c=db(),{data:o,error:oe}=await c.from('opportunities').select('id,name,description,score,metadata,problem_id').eq('id',oid).single();if(oe||!o)return NextResponse.json({error:oe?.message||'Opportunity not found'},{status:404});
  const results=await search(`${o.name} alternatives pricing reviews complaints problems`),enriched=await enrich(results,`${o.name}: ${o.description||''}`);for(const x of enriched.slice(0,10))await c.from('competitors').upsert({opportunity_id:oid,name:String(x.name||x.title||'Unknown'),url:x.url||null,description:x.description||x.snippet||'',pricing:x.pricing||null,features:Array.isArray(x.features)?x.features:[],complaints:Array.isArray(x.complaints)?x.complaints:[],strengths:Array.isArray(x.strengths)?x.strengths:[],weaknesses:Array.isArray(x.weaknesses)?x.weaknesses:[],evidence:{source:'web_search',snippet:x.snippet||x.description||''},confidence:Number(x.confidence||35)},{onConflict:'opportunity_id,name'});
  const valid=enriched.filter((x:any)=>x&&String(x.name||x.title||'').trim()); const avgConfidence=Math.round(valid.reduce((s:number,x:any)=>s+Number(x.confidence||0),0)/Math.max(1,valid.length)); const pressure=Math.max(0,Math.min(100,Math.round(valid.length*8+avgConfidence*.35))); const gap=100-pressure; const base=Number(o.score||0); const finalScore=Math.round(base*.8+gap*.2); const md=o.metadata&&typeof o.metadata==='object'?o.metadata:{};
  await c.from('opportunities').update({score:finalScore,updated_at:new Date().toISOString(),metadata:{...md,competition_research:{checked_at:new Date().toISOString(),competitors_found:valid.length,average_confidence:avgConfidence,competition_pressure:pressure,competition_gap:gap,score_before_competition:base,score_after_competition:finalScore}}}).eq('id',oid);
  return NextResponse.json({ok:true,opportunity_id:oid,found:valid.length,score:finalScore,competition_gap:gap,competitors:valid});}
